### ISSUE TITLE
The submit button is desktop-only

### ISSUE THREAD

**Issue by introwit** [voten-co/voten#103]
- As you might be already aware that the `submit` button on channels has a class of `desktop-only` (feels like it is added purposely), which as expected hides the submit button on mobile screens. Why so?

Thank you for your work on Voten :heart: 

![voten1](https://user-images.githubusercontent.com/11228182/29209353-a81e966c-7eab-11e7-886d-8ba5251c7a76.png)

**Comment by sullyfischer** [comment]
Hey Harish. Hope you're doing great. 

The submit button in the header is just a helper feature. The primary submit button is placed at the sidebar. 
I had to remove one element for mobile devices in order to keep it safe from the responsiveness aspect, and the submit button seemed the least necessary one.
