### ISSUE TITLE
Language may be too informal.

### ISSUE THREAD

**Issue by arswaw** [voten-co/voten#126]
Looking at this now, I'm concerned that the language used in [CategoryController.php](https://github.com/voten-co/voten/commit/3face0b5967ecf3c9f5410606ed287e10b658b94#diff-088fd200cc220e4a6bc2b2349c1170f4) might be overly informal.

Examples: [`1`](https://github.com/voten-co/voten/blob/3face0b5967ecf3c9f5410606ed287e10b658b94/app/Http/Controllers/CategoryController.php#L146) [`2`](https://github.com/voten-co/voten/blob/3face0b5967ecf3c9f5410606ed287e10b658b94/app/Http/Controllers/CategoryController.php#L157)

Is this something that we want to keep?

**Comment by NicolasCARPi** [comment]
Why would you want something boring and formal?

**Comment by arswaw** [comment]
@NicolasCARPi The idea is that it adds to the level of professionalism. In addition, more concise language could improve the UX because the user feedback is more to the point.

**Comment by sullyfischer** [comment]
At the moment, I like to think of Voten as a warm and friendly community instead of a social platform. I believe a bit of informality is fine. If I overdo it at some places, please lemme know! But those two examples look fine to me. 

I should also mention that there are some responses considered for not-so-normal users. For example, we haven't shadow-banned any users so far, unless when they were made by bots to spam the site. 

I guess what I'm trying to say is, when someone does something crazy, gets a crazy response!
