### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by avidican92** [voten-co/voten#369]
Has this project been abandoned?

**Comment by sullyfischer** [comment]
More like paused rather than abandoned. I like to keep working on it, but I'm in no condition to do so for at least another 6 months. 

Also, the project started as a website, and not merely an open-source script. But I couldn't do marketing and stuff without funding for any longer. 

Thus, I guess if I do continue, it should be with a pivot, maybe continue as a script only.

**Comment by avidican92** [comment]
Too bad that voten.co is down. You can’t find someone to keep it up instead?
